/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Huawei
 */
public class AddNewQuiz extends javax.swing.JFrame {
    public static long admin_id = DigitalStepsMain.myAdmins.firstAdmin().getAdmin_ID();
    /**
     * Creates new form AddNewQuizWajood
     */
    public AddNewQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nametxt = new javax.swing.JTextField();
        desctxt = new javax.swing.JTextField();
        idtxt = new javax.swing.JTextField();
        questiontxt = new javax.swing.JTextField();
        choiceAtxt = new javax.swing.JTextField();
        choiceBtxt = new javax.swing.JTextField();
        choiceCtxt = new javax.swing.JTextField();
        choiceDtxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        levelBox = new javax.swing.JComboBox<>();
        answerBox = new javax.swing.JComboBox<>();
        profileBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        BGLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Quiz");
        setMinimumSize(new java.awt.Dimension(800, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        nametxt.setBackground(new java.awt.Color(0,0,0,1));
        nametxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(nametxt);
        nametxt.setBounds(140, 130, 230, 30);

        desctxt.setBackground(new java.awt.Color(0,0,0,1));
        desctxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(desctxt);
        desctxt.setBounds(490, 130, 260, 30);

        idtxt.setBackground(new java.awt.Color(0,0,0,1));
        idtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(idtxt);
        idtxt.setBounds(140, 190, 70, 30);

        questiontxt.setBackground(new java.awt.Color(0,0,0,1));
        questiontxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(questiontxt);
        questiontxt.setBounds(140, 256, 610, 40);

        choiceAtxt.setBackground(new java.awt.Color(0,0,0,1));
        choiceAtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(choiceAtxt);
        choiceAtxt.setBounds(140, 350, 280, 40);

        choiceBtxt.setBackground(new java.awt.Color(0,0,0,1));
        choiceBtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(choiceBtxt);
        choiceBtxt.setBounds(470, 346, 280, 40);

        choiceCtxt.setBackground(new java.awt.Color(0,0,0,1));
        choiceCtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(choiceCtxt);
        choiceCtxt.setBounds(130, 446, 280, 30);

        choiceDtxt.setBackground(new java.awt.Color(0,0,0,1));
        choiceDtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(choiceDtxt);
        choiceDtxt.setBounds(470, 446, 280, 30);

        addBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addBtn.setContentAreaFilled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(299, 517, 240, 40);

        levelBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        levelBox.setForeground(new java.awt.Color(255, 102, 0));
        levelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Begginer", "Intermediate", "Advance" }));
        getContentPane().add(levelBox);
        levelBox.setBounds(280, 190, 180, 30);

        answerBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        answerBox.setForeground(new java.awt.Color(255, 102, 51));
        answerBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        getContentPane().add(answerBox);
        answerBox.setBounds(600, 190, 150, 30);

        profileBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        profileBtn.setContentAreaFilled(false);
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        getContentPane().add(profileBtn);
        profileBtn.setBounds(10, 10, 2, 70);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(50, 530, 76, 27);

        BGLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add new quiz.png"))); // NOI18N
        BGLabel.setMinimumSize(new java.awt.Dimension(800, 630));
        getContentPane().add(BGLabel);
        BGLabel.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        //insert in Quiz Table

        if (!idtxt.getText().isEmpty() && !nametxt.getText().isEmpty() && !desctxt.getText().isEmpty()
                && !questiontxt.getText().isEmpty() && !choiceAtxt.getText().isEmpty()
                && !choiceBtxt.getText().isEmpty() && !choiceCtxt.getText().isEmpty() && !choiceDtxt.getText().isEmpty()) {
            
            int quiz_id = Integer.parseInt(idtxt.getText());
            String quiz_name = nametxt.getText();
            String description = desctxt.getText();
            String level = (String) levelBox.getSelectedItem();
            String question = questiontxt.getText();
            String choice_A = choiceAtxt.getText();
            String choice_B = choiceBtxt.getText();
            String choice_C = choiceCtxt.getText();
            String choice_D = choiceDtxt.getText();
            String answer = (String) answerBox.getSelectedItem();
            
            insertDB(quiz_id,quiz_name,description,level,question,choice_A,choice_B, choice_C, choice_D, answer );
            
            JOptionPane.showMessageDialog(null, "Inserted Succusfully");
        }else{
            JOptionPane.showMessageDialog(null, "Make Sure To Enter All Data");
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        AdminProfile frame = new AdminProfile();
        frame.setVisible(true);
        close();
    }//GEN-LAST:event_profileBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit, Data will NOT be saved.", "Back To Home",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE );
        
        if(result == 0){
            Adminquizsystemfrasme frame = new Adminquizsystemfrasme();
            frame.setVisible(true);
            close();
        }
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> answerBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField choiceAtxt;
    private javax.swing.JTextField choiceBtxt;
    private javax.swing.JTextField choiceCtxt;
    private javax.swing.JTextField choiceDtxt;
    private javax.swing.JTextField desctxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JComboBox<String> levelBox;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton profileBtn;
    private javax.swing.JTextField questiontxt;
    // End of variables declaration//GEN-END:variables
    public void insertDB(int quiz_id, String quiz_name,String description, String level, String question, String choice_A,String choice_B,String choice_C,String choice_D,String answer ){
       
        Connection dbcon = DigitalStepsMain.connectDB();

        if (dbcon != null) {
            try {
                String sql = "INSERT INTO Quiz (Quiz_ID,Quiz_Name, DescriptionQ, quizLevel, Qustion, Choice_A, Choice_B,Choice_C, Choice_D, correct_anwser) VALUES (?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement st = (PreparedStatement) dbcon.prepareStatement(sql);
                st.setInt(1, quiz_id);
                st.setString(2, quiz_name);
                st.setString(3, description);
                st.setString(4, level);
                st.setString(5, question);
                st.setString(6, choice_A);
                st.setString(7, choice_B);
                st.setString(8, choice_C);
                st.setString(9, choice_D);
                st.setString(10, answer);
                st.execute();

                
                try {
                    String sql2 = "INSERT INTO administrative_update_quize VALUES (?,?)";
                    PreparedStatement st2 = (PreparedStatement) dbcon.prepareStatement(sql2);
                    st2.setInt(1, quiz_id);
                    st2.setLong(2,admin_id );
                    st2.execute();
                    System.out.println("Inserted In Admin Update Quiz Table");
                    
                } catch (Exception e) {
                    Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, e);
                }
            } catch (Exception e) {
                Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, e);
            }

        }
    }

    public void close() { // to close the current frame if we open a new one
        WindowEvent winEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winEvent);
    }
}
