/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Ms_Al
 */
public class Admins_name extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public Admins_name() {
        initComponents();
        
     
    
        goto_ADB.setOpaque(false);
    goto_ADB.setContentAreaFilled(false);
    goto_ADB.setBorderPainted(false);

    Admin_profile.setOpaque(false);
    Admin_profile.setContentAreaFilled(false);
    Admin_profile.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_profile = new javax.swing.JButton();
        goto_ADB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 630));
        getContentPane().setLayout(null);

        Admin_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_profileActionPerformed(evt);
            }
        });
        getContentPane().add(Admin_profile);
        Admin_profile.setBounds(10, 0, 70, 70);

        goto_ADB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goto_ADBActionPerformed(evt);
            }
        });
        getContentPane().add(goto_ADB);
        goto_ADB.setBounds(720, 0, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program admins names.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_profileActionPerformed
      dispose();
        AdminProfile addQuizeFrame = new AdminProfile();
addQuizeFrame.setLocationRelativeTo(null);
    addQuizeFrame.setVisible(true);

    }//GEN-LAST:event_Admin_profileActionPerformed

    private void goto_ADBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goto_ADBActionPerformed

 dispose();
        AdminHomeDashBoaedQuize addQuizeFrame = new AdminHomeDashBoaedQuize();
addQuizeFrame.setLocationRelativeTo(null);
    addQuizeFrame.setVisible(true);
    }//GEN-LAST:event_goto_ADBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admins_name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admins_name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admins_name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admins_name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admins_name().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_profile;
    private javax.swing.JButton goto_ADB;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
