

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class AdminDisplyPlayer extends javax.swing.JFrame {

    /**
     * Creates new form AdminDisplyPlayer
     */
public static long admin_id = DigitalStepsMain.myAdmins.firstAdmin().getAdmin_ID();
    
    public AdminDisplyPlayer() {
        initComponents();
    }

    public void close() {

        WindowEvent winEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Disply Player information");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setToolTipText("see your profile");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(13, 10, 70, 70);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(340, 160, 370, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "First name", "Last name", "email", "username", "password", "Phonenumber", "country", "Level" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(340, 250, 240, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 350, 260, 180);

        jButton3.setToolTipText("");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(610, 250, 110, 40);

        jButton2.setToolTipText("Go back ");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 500, 60, 60);

        jButton4.setToolTipText("");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 130, 180, 60);

        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(23, 219, 190, 70);

        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 320, 200, 70);

        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(13, 409, 210, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminDisplyPlayers.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String Pid = jTextField1.getText();
        try {

            Connection con = DigitalStepsMain.connectDB();

            Statement ste = con.createStatement();
            String ps1 = "SELECT * FROM Player WHERE Player_ID ='" + Pid + "'";
            ResultSet rs = ste.executeQuery(ps1);

            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Player with ID " + Pid + " not found in the database", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.setText("");
                jTextArea1.setText("");
                jComboBox1.setSelectedIndex(0);

            } else {

                do {
                    if (jComboBox1.getSelectedIndex() == 0) {
                        // Display player details
                        jTextArea1.setText("First name: " + rs.getString("Fname") + "\n" + "Last name: " + rs.getString("Lname") + "\n"
                                + "Country: " + rs.getString("country") + "\n" + "Phone Number: " + rs.getString("phonenumber") + "\n" + "Email: " + rs.getString("Email") + "\n" + "Password: " + rs.getString("P_password")
                                + "\n" + "Username: " + rs.getString("Username") + "\n" + "Level" + rs.getString("Plyer_Level") + "\n");

                    } else if (jComboBox1.getSelectedIndex() == 1) {
                        jTextArea1.setText("First name: " + rs.getString("Fname") + "\n");

                    } else if (jComboBox1.getSelectedIndex() == 2) {
                        jTextArea1.setText("Last name: " + rs.getString("Lname") + "\n");

                    } else if (jComboBox1.getSelectedIndex() == 3) {
                        jTextArea1.setText("Email: " + rs.getString("Email") + "\n");

                    } else if (jComboBox1.getSelectedIndex() == 4) {
                        jTextArea1.setText("Username: " + rs.getString("Username") + "\n");

                    } else if (jComboBox1.getSelectedIndex() == 5) {
                        jTextArea1.setText("Password: " + rs.getString("P_password") + "\n");

                    } else if (jComboBox1.getSelectedIndex() == 6) {
                        jTextArea1.setText("Phone Number: " + rs.getString("phoneNumber") + "\n");

                    } else if (jComboBox1.getSelectedIndex() == 7) {
                        jTextArea1.setText("Country: " + rs.getString("country") + "\n");

                    } else if (jComboBox1.getSelectedIndex() == 8) {
                        jTextArea1.setText("Level" + rs.getString("Plyer_Level") + "\n");

                    }
                    try {

                        Connection con2 = DigitalStepsMain.connectDB();
                        String sql = "INSERT INTO Administrative_Display_player (Admin_ID,Player_ID) VALUES (?,?)";
                        PreparedStatement statement = (PreparedStatement) con2.prepareStatement(sql);
                        statement.setLong(1, admin_id );
                        statement.setString(2, Pid);
                        statement.execute();

                    } catch (SQLException e) {
                        //we do not needed
//                   JOptionPane.showMessageDialog(null, "You can display a spisfic player once in each entry to this Frame ", "Warning", JOptionPane.WARNING_MESSAGE);
//                        jTextField1.setText("");
//                        jTextArea1.setText("");
//                        jComboBox1.setSelectedIndex(0);

                    }

                } while (rs.next());

            }

        } catch (SQLException sql) {
            System.out.println("wrongg");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

// TODO add your handling code here:
/// open thes comment: 
        AdminProfile A1frame = new AdminProfile();
        A1frame.setVisible(true);
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //Open here
        AdminHomeDashBoaedQuize A2frame = new AdminHomeDashBoaedQuize();
        A2frame.setVisible(true);
        close();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        Admin_mangeplayerr A3frame = new Admin_mangeplayerr();
        A3frame.setVisible(true);
        close();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
        Adminquizsystemfrasme addQuizeFrame = new Adminquizsystemfrasme();
        addQuizeFrame.setLocationRelativeTo(null);
        addQuizeFrame.setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String message = "<html><body><p style='font-size:16px;'>You will be signed out<br>and go to a worldwide competition.</p></body></html>";

        // Create a JLabel with the custom-styled message
        JLabel messageLabel = new JLabel(message);

        int choice = JOptionPane.showOptionDialog(null, messageLabel, "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        //int choice = JOptionPane.showConfirmDialog(null, "You will be signed out and go to a worldwide competition.", "Warning", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            dispose();
            // Open a new frame or perform any desired action
            WWC_frame addQuizeFrame = new WWC_frame();
            addQuizeFrame.setLocationRelativeTo(null);
            addQuizeFrame.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Admin_mangeplayerr A3frame = new Admin_mangeplayerr();
        A3frame.setVisible(true);
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDisplyPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDisplyPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDisplyPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDisplyPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDisplyPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
