
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class choose_the_type_ofquize extends javax.swing.JFrame {
public JFrame previousFramee;

   
    public choose_the_type_ofquize() {
        initComponents();
        setSize(805,630);
        setResizable(false);
        GoToHomeLevel.setOpaque(false);
        GoToHomeLevel.setContentAreaFilled(false);
        GoToHomeLevel.setBorderPainted(false);
        LessonQuizW.setOpaque(false);
        LessonQuizW.setContentAreaFilled(false);
        LessonQuizW.setBorderPainted(false);
        PublicQuiz.setOpaque(false);
        PublicQuiz.setContentAreaFilled(false);
        PublicQuiz.setBorderPainted(false);
        
    }
    
    public choose_the_type_ofquize(JFrame previousFrame) {
       this.previousFramee = previousFrame;
        initComponents();
        setSize(805,630);
    GoToHomeLevel.setOpaque(false);
        GoToHomeLevel.setContentAreaFilled(false);
        GoToHomeLevel.setBorderPainted(false);
        LessonQuizW.setOpaque(false);
        LessonQuizW.setContentAreaFilled(false);
        LessonQuizW.setBorderPainted(false);
        PublicQuiz.setOpaque(false);
        PublicQuiz.setContentAreaFilled(false);
        PublicQuiz.setBorderPainted(false);}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PublicQuiz = new javax.swing.JButton();
        LessonQuizW = new javax.swing.JButton();
        GoToHomeLevel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose a Quiz");
        setResizable(false);
        getContentPane().setLayout(null);

        PublicQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicQuizActionPerformed(evt);
            }
        });
        getContentPane().add(PublicQuiz);
        PublicQuiz.setBounds(90, 390, 220, 110);

        LessonQuizW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonQuizWActionPerformed(evt);
            }
        });
        getContentPane().add(LessonQuizW);
        LessonQuizW.setBounds(480, 150, 240, 110);

        GoToHomeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToHomeLevelActionPerformed(evt);
            }
        });
        getContentPane().add(GoToHomeLevel);
        GoToHomeLevel.setBounds(10, 510, 110, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/choose_the_type_ofquize.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LessonQuizWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonQuizWActionPerformed
        if(DigitalStepsMain.myPlayers.firstPlayer().getLevel().equals("Advance")){
            System.out.println("Navigating to Q3_1 frame...");
            Q3_1 frameQ3_1 = new Q3_1();
            frameQ3_1.setLocationRelativeTo(null);
            frameQ3_1.setVisible(true);
        }else if(DigitalStepsMain.myPlayers.firstPlayer().getLevel().equals("intermediate")){
            System.out.println("Navigating to Q2_1 frame...");
            Q2_1 frameQ2_1 = new Q2_1();
            frameQ2_1.setLocationRelativeTo(null);
            frameQ2_1.setVisible(true);
        }else if (DigitalStepsMain.myPlayers.firstPlayer().getLevel().equals("Begginer")){
            System.out.println("Navigating to Q1_1 frame...");
            Q1_1 frameQ1_1 = new Q1_1();
            frameQ1_1.setLocationRelativeTo(null);
            frameQ1_1.setVisible(true);
        } else {
            if (previousFramee instanceof BegginerHome) {
                System.out.println("Navigating to Q1_1 frame...");
                Q1_1 frameQ1_1 = new Q1_1();
                frameQ1_1.setVisible(true);
            } else if (previousFramee instanceof InterHome) {
                System.out.println("Navigating to Q2_1 frame...");
                Q2_1 frameQ2_1 = new Q2_1();
                frameQ2_1.setVisible(true);
            } else if (previousFramee instanceof AdvHome) {
                System.out.println("Navigating to Q3_1 frame...");
                Q3_1 frameQ3_1 = new Q3_1();
                frameQ3_1.setVisible(true);
            } else {
                System.out.println("Previous frame not recognized." + previousFramee.getClass().getName());
            }
        }

        // Dispose of the current frame
        dispose();
    }//GEN-LAST:event_LessonQuizWActionPerformed

    private void GoToHomeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToHomeLevelActionPerformed
        goBack();
    }//GEN-LAST:event_GoToHomeLevelActionPerformed

    private void PublicQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicQuizActionPerformed
  JOptionPane.showMessageDialog(null, "It will be developed soon!", "Warning", JOptionPane.WARNING_MESSAGE);
        dispose();
        
    }//GEN-LAST:event_PublicQuizActionPerformed
    private void goBack() {
        if (previousFramee != null) {
            previousFramee.setVisible(true);
            dispose(); // Close current frame
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose_the_type_ofquize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose_the_type_ofquize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose_the_type_ofquize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose_the_type_ofquize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose_the_type_ofquize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoToHomeLevel;
    private javax.swing.JButton LessonQuizW;
    private javax.swing.JButton PublicQuiz;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    public static void addToPlayerDisplayQuiz(){
        
    }

}
