
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author author
 */
public class QuizResult extends javax.swing.JFrame {
    /**
     * Creates new form LessonPage
     */
    public QuizResult() {
        initComponents();
        pointsL.setText(QuizQuestion1.score + "");
        if (QuizQuestion1.score <= 2) {
            LevelL.setText("Your Level is Level beginner");
        } else if (QuizQuestion1.score <= 5) {
            LevelL.setText("Your Level is Level intermediate");
        } else {
            LevelL.setText("Your Level is Level advanced");
        }
    }

    public void close() {
        WindowEvent winEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winEvent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LevelL = new javax.swing.JLabel();
        pointsL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        LevelL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LevelL.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(LevelL);
        LevelL.setBounds(130, 330, 570, 50);

        pointsL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pointsL.setForeground(new java.awt.Color(255, 255, 102));
        getContentPane().add(pointsL);
        pointsL.setBounds(500, 230, 30, 50);

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 513, 76, 70);

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDefaultCapable(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 500, 140, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huawei\\Desktop\\DigitalStepsImgs\\QuizResult.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        new BegginerHome().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        updateLevel(DigitalStepsMain.myPlayers.firstPlayer().getPlayer_ID());
        if (QuizQuestion1.score <= 2) {
            BegginerHome frame = new BegginerHome();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
            close();
        } else if (QuizQuestion1.score <= 5) {
            InterHome frame = new InterHome();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
            close();
        } else {
            AdvHome frame = new AdvHome();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
            close();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramingBasicHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramingBasicHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramingBasicHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramingBasicHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LevelL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pointsL;
    // End of variables declaration//GEN-END:variables

    public void updateLevel(int id) {
        String level = "";
        Connection dbcon = DigitalStepsMain.connectDB();
        
        if (QuizQuestion1.score <= 2) {
            level = "Beginner";
            
        } else if (QuizQuestion1.score <= 5) {
            level = "intermediate";
        } else {
            level = "Advance";
        }
        
        if (dbcon != null) {
            try {
                String sql = "UPDATE Player SET Plyer_Level = ? WHERE Player_ID = ?";
                PreparedStatement st = (PreparedStatement) dbcon.prepareStatement(sql);
                st.setInt(2, id);
                st.setString(1, level);
                st.executeUpdate();

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
}
